name: Nightly Tests

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  comprehensive-test:
    name: Comprehensive Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run comprehensive tests
        run: |
          npm run test:coverage
          npm run lint
          npm run build

      - name: Test installation as package
        run: |
          npm pack
          cd /tmp
          mkdir test-install
          cd test-install
          npm init -y
          npm install $GITHUB_WORKSPACE/*.tgz
          node -e "console.log('✅ Package installs correctly')"

  cross-platform-ios:
    name: Cross-platform iOS Test
    runs-on: macos-latest

    strategy:
      matrix:
        xcode-version: ['14.3.1', '15.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Setup Xcode ${{ matrix.xcode-version }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Test iOS compilation
        run: |
          cd ios
          pod install
          xcodebuild -workspace Plugin.xcworkspace \
                     -scheme Plugin \
                     -destination 'generic/platform=iOS' \
                     -configuration Debug \
                     build
          xcodebuild -workspace Plugin.xcworkspace \
                     -scheme Plugin \
                     -destination 'generic/platform=iOS' \
                     -configuration Release \
                     build

  dependency-security:
    name: Security & Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: License check
        run: npx license-checker --summary

  notify-results:
    name: Notify Nightly Results
    runs-on: ubuntu-latest
    needs: [comprehensive-test, cross-platform-ios, dependency-security]
    if: always()

    steps:
      - name: Evaluate results
        run: |
          if [[ "${{ needs.comprehensive-test.result }}" == "success" && \
                "${{ needs.cross-platform-ios.result }}" == "success" && \
                "${{ needs.dependency-security.result }}" == "success" ]]; then
            echo "✅ All nightly tests passed!"
          else
            echo "❌ Some nightly tests failed:"
            echo "- Comprehensive tests: ${{ needs.comprehensive-test.result }}"
            echo "- iOS tests: ${{ needs.cross-platform-ios.result }}"
            echo "- Security check: ${{ needs.dependency-security.result }}"
            exit 1
          fi